import { Video } from '@/types';

const mockVideoPool: Video[] = [
  {
    id: 'v1',
    title: 'Galatasaray - Fenerbahçe Derbisi Analizi | Sert Değerlendirme',
    channelTitle: 'Erman Toroğlu',
    channelId: 'erman-toroglu',
    thumbnail: '',
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    viewCount: '245000',
    duration: '18:34',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: false,
  },
  {
    id: 'v2',
    title: "Süper Lig'de Hakem Skandalları! Bunu Kabul Edemeyiz!",
    channelTitle: 'Erman Toroğlu',
    channelId: 'erman-toroglu',
    thumbnail: '',
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    viewCount: '189000',
    duration: '22:10',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: false,
  },
  {
    id: 'v3',
    title: "Taktik Analiz: Galatasaray'ın 4-3-3 Sistemi Nasıl Çalışıyor?",
    channelTitle: 'Uğur Karakullukçu',
    channelId: 'ugur-karakullukcu',
    thumbnail: '',
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    viewCount: '98000',
    duration: '25:45',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: false,
  },
  {
    id: 'v4',
    title: 'Beşiktaş Savunma Zaafiyeti | Detaylı Taktik İnceleme',
    channelTitle: 'Uğur Karakullukçu',
    channelId: 'ugur-karakullukcu',
    thumbnail: '',
    publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    viewCount: '76000',
    duration: '31:20',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: false,
  },
  {
    id: 'v5',
    title: 'CANLI | Cimbom Şampiyon Olur mu? Canlı Yayın Sohbeti',
    channelTitle: 'Serdar Ali Çelikler',
    channelId: 'serdar-ali-celikler',
    thumbnail: '',
    publishedAt: new Date().toISOString(),
    viewCount: '12000',
    duration: 'CANLI',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: true,
  },
  {
    id: 'v6',
    title: 'Galatasaray Transfer Gündemi | Kim Geliyor Kim Gidiyor?',
    channelTitle: 'Serdar Ali Çelikler',
    channelId: 'serdar-ali-celikler',
    thumbnail: '',
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    viewCount: '156000',
    duration: '28:50',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: false,
  },
  {
    id: 'v7',
    title: 'Süper Lig 28. Hafta Değerlendirmesi | Tüm Maçlar',
    channelTitle: 'Ali Ece',
    channelId: 'ali-ece',
    thumbnail: '',
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    viewCount: '134000',
    duration: '35:22',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: false,
  },
  {
    id: 'v8',
    title: 'CANLI | Beşiktaş Maç Sonu Değerlendirme',
    channelTitle: 'Sinan Engin',
    channelId: 'sinan-engin',
    thumbnail: '',
    publishedAt: new Date().toISOString(),
    viewCount: '8500',
    duration: 'CANLI',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: true,
  },
  {
    id: 'v9',
    title: 'Fenerbahçe 3-1 Antalyaspor | Maç Özeti ve Goller',
    channelTitle: 'FB TV / Fener Yorumcuları',
    channelId: 'fenerbahce-youtube',
    thumbnail: '',
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    viewCount: '450000',
    duration: '8:30',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: false,
  },
  {
    id: 'v10',
    title: 'Trabzonspor Hafta Sonu Maç Önü | Kadro Analizi',
    channelTitle: 'TS Medya',
    channelId: 'trabzonspor-medya',
    thumbnail: '',
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    viewCount: '67000',
    duration: '12:15',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: false,
  },
  {
    id: 'v11',
    title: 'Ali Ece ile Transfer Dedikodları | Kimler Geliyor?',
    channelTitle: 'Ali Ece',
    channelId: 'ali-ece',
    thumbnail: '',
    publishedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    viewCount: '88000',
    duration: '19:44',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: false,
  },
  {
    id: 'v12',
    title: 'CANLI | Fenerbahçe Transfer Canlı Yayın',
    channelTitle: 'FB TV / Fener Yorumcuları',
    channelId: 'fenerbahce-youtube',
    thumbnail: '',
    publishedAt: new Date().toISOString(),
    viewCount: '15000',
    duration: 'CANLI',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ytVideoId: 'dQw4w9WgXcQ',
    live: true,
  },
];

export function getMockVideosForChannels(channelIds: string[]): Video[] {
  return mockVideoPool.filter((v) => channelIds.includes(v.channelId));
}
